# Creating Neural Network II : nn.Module

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

We create a simple neural network of 3 layers.

In [2]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.lin1 = nn.Linear(1, 10)
        self.lin2 = nn.Linear(10, 1)

    def forward(self, x):
        x = F.relu(self.lin1(x))
        return self.lin2(x)

In [4]:
model = Model()
model

Model(
  (lin1): Linear(in_features=1, out_features=10, bias=True)
  (lin2): Linear(in_features=10, out_features=1, bias=True)
)

Lets do a forward pass through the network

In [11]:
a = torch.tensor([5.])
model.forward(a)

tensor([-1.2495], grad_fn=<AddBackward0>)

Parameters of the network can be accessed via state_dict

In [24]:
model.state_dict()

OrderedDict([('lin1.weight', tensor([[-0.8574],
                      [-0.2365],
                      [-0.9223],
                      [-0.6356],
                      [-0.6146],
                      [-0.1505],
                      [ 0.3377],
                      [ 0.1552],
                      [ 0.3402],
                      [ 0.0087]])),
             ('lin1.bias',
              tensor([ 0.1447, -0.1574, -0.4819,  0.0602,  0.0288, -0.8632, -0.4534,  0.7250,
                      -0.2029, -0.1412])),
             ('lin2.weight',
              tensor([[-0.1834,  0.0902, -0.1540,  0.0974,  0.2068,  0.0174, -0.1039,  0.0878,
                       -0.3026,  0.2263]])),
             ('lin2.bias', tensor([0.1073]))])

Changing the parameters of a network

In [30]:
b = torch.ones([10,1])
model.lin1.weight = torch.nn.Parameter(b)
model.lin1.weight

Parameter containing:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)

In [6]:
for parameter in model.named_parameters():
  print(parameter)

('lin1.weight', Parameter containing:
tensor([[ 0.6302],
        [-0.7521],
        [ 0.8657],
        [ 0.8939],
        [-0.2656],
        [-0.1637],
        [-0.7763],
        [ 0.7157],
        [-0.1533],
        [ 0.1167]], requires_grad=True))
('lin1.bias', Parameter containing:
tensor([-0.0434,  0.8704, -0.9272,  0.9820, -0.7549, -0.2907, -0.1777,  0.7564,
         0.4013,  0.5902], requires_grad=True))
('lin2.weight', Parameter containing:
tensor([[-0.1902,  0.3105, -0.2732, -0.2015,  0.0088, -0.0364,  0.2356,  0.2580,
          0.1321,  0.3007]], requires_grad=True))
('lin2.bias', Parameter containing:
tensor([-0.1019], requires_grad=True))


Put the model on GPU/CPU

In [10]:
model.to(device='cuda:0')

RuntimeError: ignored

In [13]:
model.eval()
print(model.forward(a))
with torch.no_grad():
  print(model.forward(a))  

tensor([-1.2495], grad_fn=<AddBackward0>)
tensor([-1.2495])


In [16]:
model.zero_grad()