# Creating Neural Network I : nn.Sequential

In [2]:
import torch
import torch.nn as nn


We construct a very basic model which takes an input and outputs a single number



In [50]:
model = nn.Sequential(
         nn.Linear(1, 10),
            nn.ReLU(),
            nn.Linear(10, 1),
            )

In [5]:
model(torch.rand(3,1))

tensor([[-0.1674],
        [-0.1559],
        [-0.1776]], grad_fn=<AddmmBackward>)

In [9]:
a = torch.sum(model(torch.rand(3,1)),dim=[0])
a

tensor([-0.3120], grad_fn=<SumBackward1>)

We perform backpropogation on the model with the .backward() command

In [10]:
a.backward()
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
)>

In [11]:
model[0].weight.grad

tensor([[ 0.1627],
        [ 0.0000],
        [ 0.0439],
        [ 0.0000],
        [-0.4093],
        [ 0.0000],
        [ 0.0000],
        [-0.0466],
        [ 0.1612],
        [ 0.1741]])

## Training the Network from scratch manually.

Simple manual loop to train the network

In [61]:
model = nn.Sequential(
         nn.Linear(1, 10),
            nn.ReLU(),
            nn.Linear(10, 1),
            )
X = torch.rand(1000,1)
Y = X**2
for i in range(100):
  out = model(X)
  loss = torch.sum((out-Y)**2,dim=0)
  loss.backward()
  dx1 = model[0].weight.grad
  dx2 = model[2].weight.grad
  db1 = model[0].bias.grad
  db2 = model[2].bias.grad
  with torch.no_grad():
    model[0].weight -= 0.0001 * dx1
    model[2].weight -= 0.0001 * dx2
    model[0].bias -= 0.0001 * db1
    model[2].bias -= 0.0001 * db2
  model.zero_grad()

  

In [59]:
X = torch.rand(2,1)
print(X**2)
model(X)

tensor([[0.2889],
        [0.1312]])

## Training Network using an optimizer

Training the network using an optimizer

In [68]:
model = nn.Sequential(
         nn.Linear(1, 10),
            nn.ReLU(),
            nn.Linear(10, 1),
            )
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

X = torch.rand(1000,1)
Y = X**2
for i in range(100):
  out = model(X)
  loss = torch.sum((out-Y)**2,dim=0)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

In [69]:
X = torch.rand(2,1)
print(X**2)
model(X)

tensor([[0.5076],
        [0.6510]])


tensor([[0.5414],
        [0.6235]], grad_fn=<AddmmBackward>)